global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['host.docker.internal:15692']  # Use container name if using Docker
        labels:
          cluster: 'rabbitmq-cluster-1'
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          server: 'production-host'

  - job_name: 'mongodb'
    static_configs:
      - targets: ['host.docker.internal:9216']
        labels:
          database: 'production-mongodb'
    metrics_path: '/metrics'
